### ISSUE TITLE
Angular 5

### ISSUE THREAD

**Issue by Brachacz** [korniychuk/angular-autofocus-fix#4]
Hi!
Can I count on this plugin to be updated for Angular 5?
I use it in an internal corporate project alongside Angular 5.2.6 and it works as expected, though Angular dependency version number is set for 4.x.

Probably it's just a quick dependency version bump for you :)

**Comment by leonetosoft** [comment]
Also would like!
I use it in projects already in production.

**Comment by ancor-dev** [comment]
Hello guys, I will try to fix it in some days

**Comment by kopach** [comment]
Hi guys. Can we have it updated to angular 6 also? 😊

**Comment by korniychuk** [comment]
Fixed.
* For Angular 2/4 please use old version. `angular-autofocus-fix` package.
* For Angular 5/6/7/8+ please use `ngx-autofocux-fix` package
